import path from 'path';
import { GenerationContext, TemplateInput } from './types.js';

const RISK_CATEGORY_TO_DIR: Record<string, string> = {
  FINANCIAL: '1_FINANCIAL',
  DEPENDENCY: '2_DEPENDENCY',
  TECHNICAL: '3_TECHNICAL',
  APPLICATION: '4_ APPLICATION',
  ORGANIZATIONAL: '5_ORGANIZATIONAL',
  CONTRACT: '6_CONTRACT',
  HUMAN_ERROR: '7_HUMAN_ERROR',
  COMPLIANCE: '8_COMPLIANCE'
};

function toYamlArray(items: string[], indent: number = 2): string {
  const prefix = ' '.repeat(indent);
  if (items.length === 0) {
    return `${prefix}[]`;
  }
  return items.map((item) => `${prefix}- ${item}`).join('\n');
}

function normalizeDate(value?: string): string {
  if (!value) return new Date().toISOString().split('T')[0];
  if (value.includes('T')) return value.split('T')[0];
  return value;
}

export function getTargetPath(catalogueDir: string, input: TemplateInput): string {
  const suffix = input.profile === 'fidleg' ? '.FIDLEG' : '';

  if (input.entity === 'risk') {
    const category = (input.category ?? 'TECHNICAL').toUpperCase();
    const categoryDir = RISK_CATEGORY_TO_DIR[category] ?? RISK_CATEGORY_TO_DIR.TECHNICAL;
    return path.join(catalogueDir, 'risks', categoryDir, `${input.id}${suffix}.md`);
  }

  if (input.entity === 'indicator') {
    return path.join(catalogueDir, 'indicators', `${input.id}${suffix}.md`);
  }

  return path.join(catalogueDir, 'measures', `${input.id}${suffix}.md`);
}

function buildRiskMarkdown(input: TemplateInput, ctx: GenerationContext): string {
  const category = (input.category ?? 'TECHNICAL').toUpperCase();
  const scopes = input.scopes && input.scopes.length > 0 ? input.scopes : ['APPLICATION'];
  const owners = input.owners && input.owners.length > 0 ? input.owners : ['INVESTOR'];
  const indicators = input.indicators ?? [];
  const measures = input.measures ?? [];
  const extensions = ctx.profile === 'fidleg' ? '\nextensions:\n  - fidleg' : '';
  const fidlegExt =
    ctx.profile === 'fidleg'
      ? `\nregulatoryExtensions:\n  fidleg:\n    fidlegImpactCategory: CLIENT_INFORMATION_DEFICIENCY\n    triggeredFidlegActions: []`
      : '';

  return `# ${input.title}

\`\`\`yaml
id: ${input.id}
title: ${input.title}
category: ${category}
type: HYBRID
scopes:
${toYamlArray(scopes)}
owners:
${toYamlArray(owners)}
severity: MEDIUM
probability: MEDIUM
impact: MEDIUM
objectives:
  - type: VALUE
    direction: DECREASE
    goal: INCREASE
indicators:
${toYamlArray(indicators)}
measures:
${toYamlArray(measures)}${extensions}${fidlegExt}
\`\`\`

## Description

${input.description}

## Context

Generated by the agent template pipeline. Expand this section with domain-specific context and assumptions.

## Scope Justification

The selected scope reflects where this risk materializes operationally and where control actions can be applied.

## Rationale for Action

This risk entry is generated in English-first mode for operator review and downstream automation.
`;
}

function buildIndicatorMarkdown(input: TemplateInput, ctx: GenerationContext): string {
  const day = normalizeDate(input.date ?? ctx.nowDate);
  const extensions = ctx.profile === 'fidleg' ? '\nextensions:\n  - fidleg' : '';
  const fidlegExt =
    ctx.profile === 'fidleg'
      ? `\nregulatoryExtensions:\n  fidleg:\n    fidlegTriggerEvent: CRITICAL_CLIENT_INFO_UPDATE_REQUIRED\n    triggeredFidlegActions: []`
      : '';

  return `# ${input.title}

\`\`\`yaml
id: ${input.id}
title: ${input.title}
version: "1.0"
lastUpdate: ${day}
description: ${input.description}
preconditions: []
methodology: []
limitations: []
computation:
  frequency: daily
  dataSources:
    - type: api
thresholds:
  veryHigh: "n/a"
  high: "n/a"
  medium: "n/a"
  low: "n/a"
  veryLow: "n/a"${extensions}${fidlegExt}
\`\`\`

## Description

${input.description}

## Preconditions

- Data source availability
- Stable measurement interval

## Methodology

- Define the metric and data collection cadence
- Monitor threshold drift over time

## Limitations

- Baseline thresholds must be calibrated with historical data
`;
}

function buildMeasureMarkdown(input: TemplateInput, ctx: GenerationContext): string {
  const day = normalizeDate(input.date ?? ctx.nowDate);
  const impactPotential = input.impactPotential ?? 'MEDIUM';
  const difficulty = input.difficulty ?? 'MEDIUM';
  const extensions = ctx.profile === 'fidleg' ? '\nextensions:\n  - fidleg' : '';
  const fidlegExt =
    ctx.profile === 'fidleg'
      ? `\nregulatoryExtensions:\n  fidleg:\n    relevantArticles:\n      - FIDLEG_Art8\n    regulatoryRequirement: RECOMMENDED`
      : '';

  return `# ${input.title}

\`\`\`yaml
id: ${input.id}
title: ${input.title}
type: Measure
version: "1.0"
lastUpdate: ${day}
description: ${input.description}
impactPotential: ${impactPotential}
difficulty: ${difficulty}
riskReductionScope:
  severity: true
  likelihood: true
  persistence: false${extensions}${fidlegExt}
\`\`\`

## Description

${input.description}

## Preconditions

- The responsible team can execute the measure in the target environment.

## Implementation

- Define owner and rollout timeline
- Add monitoring hooks and fallback actions
`;
}

export function generateMarkdown(input: TemplateInput, ctx: GenerationContext): string {
  if (input.entity === 'risk') return buildRiskMarkdown(input, ctx);
  if (input.entity === 'indicator') return buildIndicatorMarkdown(input, ctx);
  return buildMeasureMarkdown(input, ctx);
}
